apiVersion: v1
kind: Service
metadata:
  name: gitbook-service
  namespace: gitbook
  labels:
    app: gitbook
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: gitbook
  type: ClusterIP

